disabled_rules:
  - trailing_comma
  - identifier_name
  - void_return
  - operator_whitespace
  - nesting
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - type_name
  - todo
  - large_tuple

line_length: 240

indentation_width: 4

function_body_length:
  - 50

function_parameter_count:
  warning: 8
  error: 8

included:
  - Sources
  - Tests
