name: Test Archive

on: [push]

jobs:
  archive:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run tests
        run: swift test
